# Rakefile for assembling pdftk and pdfocr

import "../lib/tasks/log.rake"
require "../lib/container"

task:default => [ :pdftk, :pdfocr ]

task:pdftk do
  log "Creating pdftk"
  pdftk = ContainerFactory.load("../config", "pdftk")
  sh pdftk.create

  log "starting pdftk"
  sh pdftk.start_then_wait
end

task:pdfocr do
  log "Creating pdfocr"
  pdfocr = ContainerFactory.load("../config", "pdfocr")
  sh pdfocr.create

  log "starting pdfocr"
  sh pdfocr.start_then_wait
end

task:clean do
  log "cleaning up containers"
  begin
    sh pdftk.rm
  rescue => err
  end
end
