# Rakefile for assembling pdftk and pdfocr

import "../lib/tasks/log.rake"
require "../lib/container"

task:default => [ :pdftk, :pdfocr ]

task:pdftk do
  log "in pdftk"
  pdftk = ContainerFactory.load("../config", "pdftk")
  sh pdftk.create

  log "starting pdftk"
  sh "instance=$(#{pdftk.start}) ; sudo docker wait ${instance}"
end

task:pdfocr do
  log "in pdfocr"
  pdfocr = ContainerFactory.load("../config", "pdfocr")
  sh pdfocr.create

  log "starting pdfocr"
  sh "instance=$(#{pdfocr.start}) ; sudo docker wait ${instance}"
end

task:clean do
  log "cleaning up containers"
  sh 'sudo docker rm piper.pdftk piper.pdfocr'
end
