# Rakefile for assembling pdftk and pdfocr

import "../lib/tasks/log.rake"
require "../lib/container"

task:default => [ :pdftk, :pdfocr ]

task:pdftk do
  log "in pdftk"
  pdftk = ContainerFactory.load("../config", "pdftk")
  sh pdftk.create
end

task:pdfocr do
  log "in pdfocr"
end

