#Rakefile - rake for .md -> html -> .erb.html -> .pdf

# replace_extension - .html => pdf
def replace_ext fname, ext
  fname =~ /(.*\.).*/
  "#{$1}#{ext}"
end

task :default => ['template.erb.html', :pdfs] 

file 'template.erb.html' => 'template.html' do
  sh './template.rb'
  touch 'template.erb.html'
end

file 'header.html' => 'header.md' do
  sh './redcarpet.rb header.md > header.html'
end

file 'template.html' => 'template.md' do
  sh './redcarpet.rb template.md > template.html'
end

task :clean do
  rm_f 'template.erb.html'
  rm_f Dir['MRN*.html']
end

task :pdfs do
  Dir['MRN_*.html'].each do |file|
    sh "./dowk.sh #{file} #{replace_ext(file, 'pdf')}"
  end
end
