#Rakefile - rake for .md -> html -> .erb.html -> .pdf

task :default => ['template.erb.html'] 

file 'template.erb.html' => 'template.html' do
  sh './template.rb template.html'
  touch 'template.erb.html'
end

file 'template.html' => 'template.md' do
  sh './redcarpet.rb template.md > template.html'
end
