# Rakefile for MDSL to MD files

# execute the mdgen Ruby script from the sibling pdf_pipeline project
def mdgen source, dest
  sh "../../../pdf_pipeline/bin/mdgen #{source} > #{dest}"
end

mdsl_files = FileList['*.mdsl']

task :default => [:md]
task :md => mdsl_files.ext('.md')

rule '.md' => '.mdsl' do |t|
  mdgen t.source, t.name
end


