--- !ruby/object:Config
image_name: pdftk
container_name: pdftk
registry: vagrant
tag: v0.1
arg: "/script/pdftk.sh"
vols_hash:
  "/home/vagrant/src/docker/pipeline/script": "/script"
  "/home/vagrant/src/docker/pipeline/input": "/input"
  "/home/vagrant/src/docker/pipeline/working": "/working"
  "/home/vagrant/src/docker/pipeline/output": "/output"
